apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090  # Adjust the URL as needed
  isDefault: true
  editable: true
  jsonData:
    tlsAuth: false
    tlsAuthWithCACert: false