{
 "title": "TdA Deploy Overview",
 "time": { "from": "2024-02-07T13:25:58.015Z", "to": "2024-02-07T13:41:21.299Z" },
 "panels": [
  {
   "title": "Memory Usage Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name!~\"\"} / (1024 * 1024))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Total System",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_system=~\"true\"}) / ( 1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SYSTEM Container Memory  Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_system=\"true\"} / (1024*1024)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "SYSTEM CPU usage per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{container_label_system=~\"true\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory  Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_system!~\"true\", container_label_traefik_enable=\"true\"} / 1024*1024",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU usage per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_system!~\"true\", container_label_traefik_enable=\"true\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Transmit MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{container_label_system!~\"true\", container_label_traefik_enable=\"true\"} / 1048576",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Network Receiving MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{container_label_system!~\"true\", container_label_traefik_enable=\"true\"} / 1048576",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "container_network_receive_errors_total{container_label_system!~\"true\", container_label_traefik_enable=\"true\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "container_network_transmit_errors_total{container_label_system!~\"true\", container_label_traefik_enable=\"true\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "container_network_transmit_packets_dropped_total{container_label_system!~\"true\", container_label_traefik_enable=\"true\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}