---
- name: Create a network for redis
  docker_network:
    name: "{{ redis_network }}"

- name: Ensure redis directory exists
  file:
    path: "{{ redis_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0777"

- name: Run Redis
  docker_container:
    name: "{{ redis_container_name }}"
    image: "redis:{{ redis_docker_tag }}"
    restart_policy: unless-stopped
    recreate: false
    volumes:
      - "{{ redis_data_dir }}:/data"
    networks:
      - name: "{{ redis_network }}"
    labels:
      traefik.enable: "false"
    stop_signal: SIGQUIT

