openapi: "3.0.0"
info:
  version: "1"
  title: ""
  description: ""
paths:
  /application/{team-id}:
    get:
      operationId: "GET-application"
      description: ""
      parameters:
        - in: "path"
          name: "team-id"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/application"
        404:
          description: ""
          content:
            application/json:
              schema:
                type: "string"
    delete:
      operationId: "DELETE-application"
      description: ""
      parameters:
        - in: "path"
          name: "team-id"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: "string"
        500:
          description: ""
          content:
            application/json:
              schema:
                type: "string"
    post:
      operationId: "DEPLOY-application"
      description: ""
      parameters:
        - in: "path"
          name: "team-id"
          required: true
          schema:
            type: "string"
        - in: "query"
          name: "subdomain"
          schema:
            type: "string"
        - in: "query"
          name: "registry-credentials"
          schema:
            type: "string"
        - in: "query"
          name: "image-name"
          schema:
            type: "string"
        - in: "query"
          name: "redeploy"
          schema:
            type: "string"
        - in: "query"
          name: "callback-url"
          schema:
            type: "string"
      responses:
        202:
          description: ""
          content:
            application/json:
              schema:
                type: "string"
  /application:
    get:
      operationId: "GET-all-applications"
      description: ""
      parameters: []
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/application"
    delete:
      operationId: "DELETE-all"
      description: ""
      parameters:
        - in: "query"
          name: "delete-all-applications"
          schema:
            type: "boolean"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: "string"
        400:
          description: ""
          content:
            application/json:
              schema:
                type: "string"
components:
  securitySchemes:
    BasicAuth:  
      type: "http"
      scheme: "basic"
  schemas:
    application:
      type: "object"
      properties:
        team_id:
          type: "string"
        container_id:
          type: "string"
        container_name:
          type: "string"
        route:
          type: "string"
        subdomain:
          type: "string"
        image_name:
          type: "string"
