# Dockerfile for the worker
FROM python:3.11-slim-buster

WORKDIR /app

COPY . /app

ENV PYTHONPATH /app/src

RUN pip install pipenv \
    && pipenv install --system --deploy

# Grant access to docker.sock to allow container parallelism
VOLUME /var/run/docker.sock

CMD ["python", "src/worker.py"]