---
- name: Install python3-pip and passlib
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present

- name: Install Passlib Python Library
  ansible.builtin.pip:
    name: passlib
    state: present

- name: Check if htpasswd is a directory
  stat:
    path: "{{ htpasswd_file }}"
  register: htpasswd_stat

- name: Delete htpasswd directory if it exists
  file:
    path: "{{ htpasswd_file }}"
    state: absent
  when: htpasswd_stat.stat is defined and htpasswd_stat.stat.isdir

- name: Create htpasswd file
  htpasswd:
    path: "{{ htpasswd_file }}"
    name: "{{ htpasswd_user }}"
    password: "{{ htpasswd_password }}"
    crypt_scheme: bcrypt
    owner: "root"
    group: "root"
    mode: "0644"
    create: yes

- name: Run Docker Registry
  docker_container:
    name: registry
    image: registry:2
    ports:
      - "5000:5000"
    restart_policy: always
    volumes:
      - "/var/lib/registry:/var/lib/registry"
      - "{{ htpasswd_file }}:/auth/htpasswd"
    env:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
    labels:
      system: "true"
      traefik.enable: "true"
      traefik.http.routers.registry.rule: "Host(`{{ base_domain }}`)"
      traefik.http.routers.registry.entrypoints: "websecure"
      traefik.http.routers.registry.tls.certresolver: "tlsResolver"
    networks:
      - name: web
