---
- name: Create the monitoring / traefik network
  docker_network:
    name: web
    driver_options:
      com.docker.network.bridge.name: traefik0

#- name: Create the monitoring / traefik network for system containers
#  docker_network:
#    name: system
#    driver_options:
#      com.docker.network.bridge.name: traefik1

- name: Create the traefik directory
  file:
    path: "{{ traefik_dir }}"
    state: directory
    owner: root
    group: root

- name: Copy the traefik configuration file
  template:
    src: traefik.yml.j2
    dest: "{{ traefik_dir }}/traefik.yml"
    owner: root
    group: root
    mode: "0644"

- name: Copy the traefik dynamic configuration file
  template:
    src: dynamic_conf.yml.j2
    dest: "{{ traefik_dir }}/dynamic_conf.yml"
    owner: root
    group: root
    mode: "0644"

- name: Check if acme.json is a directory
  stat:
    path: "{{ traefik_dir }}/acme.json"
  register: acme_stat

- name: Delete acme.json directory if it exists
  file:
    path: "{{ traefik_dir }}/acme.json"
    state: absent
  when: acme_stat.stat is defined and acme_stat.isdir is defined and acme_stat.stat.isdir

- name: Set permissions for acme.json
  # TODO: On a new run creates directory instead of file
  file:
    path: "{{ traefik_dir }}/acme.json"
    state: touch
    owner: root
    group: root
    mode: "0600"

- name: Create the traefik container
  docker_container:
    name: traefik
    image: traefik:2.2
    restart_policy: unless-stopped
    recreate: true
    cpu_period: 100000
    cpu_quota: 50000
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ traefik_dir }}/traefik.yml:/etc/traefik/traefik.yml"
      - "{{ traefik_dir }}/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml"
      - "{{ traefik_dir }}/acme.json:/acme.json"
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      system: "true"
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`{{ traefik_api_url }}`)"
      traefik.http.routers.traefik.entrypoints: "websecure"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.middlewares: "traefik-auth"
      traefik.http.middlewares.traefik-auth.basicauth.users: "{{ traefik_api_user }}:{{ traefik_api_password | password_hash('blowfish','1234567890123456789012') }}"
      traefik.http.routers.traefik.tls.certresolver: "tlsResolver"
    networks:
      - name: web
    etc_hosts:
      host.docker.internal: "host-gateway"
