---
- name: Copy project files to the remote server
  copy:
    src: "{{ source_app_dir }}"
    dest: "{{ target_app_dir }}"
    owner: root
    group: root
    mode: "0755"

- name: Build Docker image for Flask app
  community.general.docker_image:
    name: dynamic_deploy_app
    source: build
    build:
      path: "{{ target_app_dir }}"
    state: present
    force_source: yes

- name: Run Docker container for Flask app
  docker_container:
    name: dynamic_deploy_app_container
    image: dynamic_deploy_app
    restart_policy: unless-stopped
    recreate: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.http.routers.deploy.rule: "Host(`{{ deploy_url }}`)"
    networks:
      - name: web
    env:
      BASE_DOMAIN: "{{ base_domain}}"
      TRAEFIK_NETWORK: web